spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library


mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.admeya.spring.mongock.changelog